Esri/military-tools-geoprocessing-toolbox

utils/test/visibility_tests/LowestPointsTestCase.py
utils/test/visibility_tests/VisibilityTestSuite.py

also a missed rename in FindLocalPeaksTestCase

Add Lowest Points Test Case

---

utils/test/visibility_tests/HighestPointsTestCase.py
utils/test/visibility_tests/VisibilityTestSuite.py

@mfunk, please review and merge.

Created HighestPoints unit test

---

utils/test/TestRunner.py
utils/test/visibility_tests/FindLocalPeaksTestCase.py
utils/test/visibility_tests/HighestPointsTestCase.py
utils/test/visibility_tests/LinearLineOfSightTestCase.py
utils/test/visibility_tests/LowestPointsTestCase.py
utils/test/visibility_tests/RadialLineOfSightTestCase.py

Got a partial fix on the tests not picking up the tool failures. We are still getting a "exception occurred while handling exception"

MF: Update visibility tests for error handing changes

---

toolboxes/scripts/ConvertCoordinates.py
toolboxes/scripts/PolylineToPolygon.py
utils/test/TestRunner.py
utils/test/conversion_tests/ConvertCoordinatesTestCase.py

Did some internal refactoring of tool to use methods (smaller code footprint) and removed dependency on AddUniqueRowID tool.

Updates to ConvertCoordinates

---

utils/test/TestKickStart.bat
utils/test/TestRunner.py
utils/test/conversion_tests/ConversionUtilitiesTestCase.py
utils/test/conversion_tests/ConvertCoordinatesTestCase.py
utils/test/conversion_tests/TableToEllipseTestCase.py
utils/test/conversion_tests/TableToLineOfBearingTestCase.py
utils/test/conversion_tests/TableToPointTestCase.py
utils/test/conversion_tests/TableToPolygonTestCase.py
utils/test/conversion_tests/TableToPolylineTestCase.py
utils/test/conversion_tests/TableToTwoPointLineTestCase.py
utils/test/distance_tests/RangeRingUtilsTestCase.py
utils/test/visibility_tests/AddLLOSFieldsTestCase.py
utils/test/visibility_tests/AddRLOSObserverFieldsTestCase.py
utils/test/visibility_tests/FindLocalPeaksTestCase.py
utils/test/visibility_tests/HighestPointsTestCase.py
utils/test/visibility_tests/LinearLineOfSightTestCase.py
utils/test/visibility_tests/LowestPointsTestCase.py
utils/test/visibility_tests/RadialLineOfSightTestCase.py
utils/test/visibility_tests/VisibilityUtilitiesTestCase.py

Fixed issues where scratch GDB was going to testdata folder.
Also changed test to run on Jenkins
Made changes to test cases to check if scratchGDB exited in utils/tests, and create one there if not.
TestKickStart.bat now runs 'python' instead of 'py'.
N/A
scratch data was created in wrong place and never removed.
Tests were not being run on Jenkins.
Cannot test Jenkins fix until integrated into dev branch.

fixed scratchGDB problems and Jenkins run issue

---

.gitignore
toolboxes/scripts/ConversionUtilities.py

See Issue #208
Join field was incorrectly set to "text" instead of "long" in polylineToPolygon.
Also optimized polylineToPolygon a bit (about 20-30%)

Issue #208 fix

---

.gitignore
toolboxes/scripts/ConversionUtilities.py
toolboxes/scripts/VisibilityUtilities.py
utils/test/.gitignore
utils/test/ArcGISProTestKickStart.bat
utils/test/ArcMapTestKickStart.bat
utils/test/TestRunner.py
utils/test/conversion_tests/ConvertCoordinatesTestCase.py
utils/test/distance_tests/RangeRingUtilsTestCase.py
utils/test/visibility_tests/VisibilityUtilitiesTestCase.py

I also merged with the dev upstream, just to make sure I was testing against the latest dev

Changes to branch to get Pro tests to run

---

toolboxes/scripts/AddLLOSFields.py
toolboxes/scripts/AddRLOSObserverFields.py
toolboxes/scripts/ConversionUtilities.py
toolboxes/scripts/FindLocalPeaks.py
toolboxes/scripts/HighestPoints.py
toolboxes/scripts/LinearLineOfSight.py
toolboxes/scripts/LowestPoints.py
toolboxes/scripts/RadiaLineOfSight.py
toolboxes/scripts/RangeRingFromMinMaxTable.py
toolboxes/scripts/RangeRingMinMax.py
toolboxes/scripts/RangeRingsFromInterval.py
toolboxes/scripts/TableTo2PointLine.py
toolboxes/scripts/TableToEllipse.py
toolboxes/scripts/TableToLineOfBearing.py
toolboxes/scripts/TableToPoint.py
toolboxes/scripts/TableToPolygon.py
toolboxes/scripts/TableToPolyline.py
toolboxes/scripts/VisibilityUtilities.py

**Issue #204** 
replaced all statements from:
if debug == False and len(deleteme) > 0: 
to
if len(deleteme) > 0: 
**Issue #205**
If the RADIUS2 field exists in the input feature class the script is supposed to use the value contained within, what is actually being returned from line 1405 in VisibilityUtilities.py is a list not a value, hence the script then throwing errors on later actions:
inputRadiusOfObserver = _getUniqueValuesFromField(inputObserverFeatures,"RADIUS2")[:1]
This line should be changed to:
inputRadiusOfObserver = _getUniqueValuesFromField(inputObserverFeatures,"RADIUS2")[:1][0]
To return the first (and only) value in the list

Address issues #204 & #205

---

toolboxes/scripts/VisibilityUtilities.py

On investigation it appears that if the number of peaks (inverted sink holes) within the elevation area of input is less than the Number of Peaks determined by the user, it will throw an error (due to trying to access an array value greater than the array length).
The solution was to set the number of peaks to the number of sink holes (if less than the user input) and inform the user that this has been done.
This got me thinking what would happen if no sinks holes are found (a very small or flat AOI). As I expected this also caused the code to error, so I have also added a error check for this.

Address Issue #217

---

toolboxes/scripts/VisibilityUtilities.py

Sorry didnt realise that Matt already had a _clipRasterToArea function in the script that uses the extract by mask, swapped the code to use that instead for consistancy

Update to #207

---

README.md

See #245 
Note: Looks like the v1.1 should be marked "protected" as well

Update required Pro version to 1.4+

---

README.md

Change Pro requirement to 1.4 for v1.0

---

utils/test/ArcMapTestKickStart.bat

Fix issue that came up testing with Jenkins

Fix python launch for Jenkins

---

toolboxes/scripts/RadialLineOfSightAndRange.py
utils/test/arcpyAssert.py
utils/test/conversion_tests/TableToEllipseTestCase.py
utils/test/conversion_tests/TableToLineOfBearingTestCase.py
utils/test/conversion_tests/TableToPointTestCase.py
utils/test/visibility_tests/VisibilityUtilitiesTestCase.py

Some additional fixes to #250

---

toolboxes/scripts/ConversionTools.py

adding conversion tools for collaboration

Adding conversion tools file

---

toolboxes/scripts/RadialLineOfSightAndRange.py
toolboxes/scripts/VisTools.py

Fix for RadialLineOfSightAndRange in Pro

Fix for RadialLineOfSightAndRange in Pro

---

toolboxes/scripts/GRGTools.py

Addressed [#670](https://github.com/Esri/solutions-geoprocessing-toolbox/issues/670)
Addressed [#670](https://github.com/Esri/solutions-geoprocessing-toolbox/issues/670)
This fix will eliminate confusion of creating rows and columns for a GRG.
Tested in ArcMap

Changed display names for rows and columns

---

Contents.md
README.md

Updates to the Readme.md and Contents.md file to reflect new Military Tools python toolbox and contents, and supporting scripts and layers.

Bb 275 update readme for repo

---

toolboxes/scripts/ConversionUtilities.py

Fixes #254 
Lines by default were being created with a `CLOSE` option. Set it to `NO_CLOSE` and lines are now created correctly
N/A
Fixes #254 
In ArcMap

Addresses issue 254

---

toolboxes/scripts/ConversionTools.py
toolboxes/scripts/GRGTools.py

Fixed capitalization of some tools and renamed the GRG toolset

Fixed capitalization for Military Tools 

---

toolboxes/scripts/GRGTools.py
toolboxes/scripts/GRGUtilities.py
utils/test/grg_tests/GRGCreateGRGFromPointTestCase.py

Addresses:
1. The Create GRG from Point tool failing in Pro 2.2 (and probably before that) - https://github.com/Esri/solutions-geoprocessing-toolbox/issues/667
2. Rotation Angle Unit test failing when running in Pro
3. Adds test for Rotation Angle
4. Refactor GRGUtilities.RotateFeatureClass to use DA cursor
https://github.com/Esri/solutions-geoprocessing-toolbox/issues/667
Manual: Pro, ArcMap; Automated: Unit Tester

GRG from Point Tool with rotation angle fails to rotate

---

utils/test/conversion_tests/ConvertCoordinatesTestCase.py

Adds logic to test if the fields were added

Adds logic to test if the fields were added

---

utils/test/conversion_tests/TableToPolylineTestCase.py

Counts number of vertices in output line features and compares to the
number of rows in input table

Added test case for issue 254

---

utils/test/grg_tests/GRGCreateGRGFromAreaTestCase.py

Added test using a compare two list created from OID attribute and the Grid attribute. If they are equal the test passes.
Added numeric tests for grg from area. 
adding test four in reference issue: 
https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/276

Added the fourth test to test numeric labels

---

toolboxes/scripts/VisTools.py
toolboxes/scripts/VisibilityUtilities.py

A user could add bogus Observer and Target input parameters. This fix will validate if those input parameters are legitimate. 
Added defensive checks in the `execute` function to check for valid observer and target input parameters.
Addresses #302 
User can supply bogus observer and target input parameters
Tested in Pro and ArcMap

Added checks for observer and target

---

toolboxes/scripts/VisibilityUtilities.py

Added code to validate that an input area was added and that it contains
a feature

Add validation for issue 320 check for input area

---

utils/test/TestRunner.py

(forgot to revert prior to merge)

Modifying testrunner to include all tests.

---

utils/test/TestRunner.py
utils/test/distance_tests/RangeRingUtilsTestCase.py

Automated test for issue 311, the added code iterates on the output ring features, adding the Range values to a list. It then gets the set of unique values from that list (because if n input centers are used, you get n copies of each value), sorts and compares to the original input list of ranges.

Bb 311 automated test retry

---

toolboxes/scripts/VisTools.py

Change output layer names to match industry standards
1. FullWedge is now Range
2. Wedge if now Field of View
3. viewshed is now Viewshed
Addresses #264 
fullwedge and wedge is confusing and no meaning in the industry. 
ArcGIS Pro and ArcMap

Changed layer names to industry standard

---

toolboxes/scripts/VisTools.py

Parameters for the tool were incorrect. Changes added fixes the issue. Similar #331 
[Line 720](https://github.com/Esri/military-tools-geoprocessing-toolbox/compare/kg/issue-302?expand=1#diff-e636f83b4d2e88d82a5dd4763b1b5763R720) fixes the issue

Corrected parameter order

---

toolboxes/scripts/VisTools.py

Issue #331 - correct parameter errors introduced in PR #315 to RLOS
Issue #331 - correct parameter errors introduced in PR #315 to RLOS
#331 #315

Correct parameter errors introduced in PR #315 for RLOS

---

pythonpackage/militarytools/GRGUtilities.py

Sending a string to arcpy.Exists() method instead of a GP object.
arcpy.Exists() was throwing an error when executing on an input parameter that is a GP object.
Addresses #358 
Addresses #358

Addresses #358

---

Contents.md
README.md

Update to the markdown and contents files

updated files to reflect changes.

---

Geoprocessing/scripts/GRGUtilities.py

This fix addresses #366 
Input point needs to be projected to Web Mercator in order for the tool to run successfully.
Addresses #366 
Addresses #366 
Tested in ArcGIS Pro 2.2

Addresses #366

---

pythonpackage/militarytools/GRGUtilities.py

syncing the python package with the geoprocessing folder.

updates to the python package

---

Geoprocessing/scripts/GRGTools.py
pythonpackage/militarytools/GRGTools.py

Lw grg referance symbol layer issue

---

tools/setup.py

Linking to :  https://github.com/ArcGIS/solutions-defense/issues/929

Update Conda Package version

---

tools/militarytools/esri/toolboxes/layers/LLOS_OutputLLOS.lyrx
tools/militarytools/esri/toolboxes/layers/LLOS_OutputSightLines.lyrx
tools/militarytools/esri/toolboxes/layers/LLOS_Output_Observers.lyrx
tools/militarytools/esri/toolboxes/layers/LLOS_Output_Targets.lyrx
tools/militarytools/esri/toolboxes/scripts/VisTools.py

See #387 - ArcMap version of lyr files where not displaying correctly/consistently on Pro so switched tool to use the Pro versions (lyrx) that were already available in the repo.
Should match ArcMap output now:

Issue 387 Update Pro tool to use Pro lyrx

---

tools/militarytools/esri/toolboxes/scripts/RadialLineOfSightAndRange.py
tools/militarytools/esri/toolboxes/scripts/VisibilityUtilities.py

See Issue: #401 - Adds check that input points fall within surface before proceeding

#401 Add check that points fall within surface

---

tools/militarytools/esri/toolboxes/scripts/ConvertCoordinates.py

See: #407 - adds numeric lat/lon to conversion outputs

Issue #407 - add numeric lat/lon output

---

tools/militarytools/esri/toolboxes/scripts/GRGTools.py
tools/militarytools/esri/toolboxes/scripts/GRGUtilities.py
tools/militarytools/esri/toolboxes/scripts/VisTools.py

Issue #395 - added license checks to the tools

Add tool license checks

---

tools/setup.py

Update Conda Version to match MT build number

Update Conda Version to match MT build number

---

tools/setup.py

Update conda package version from 3.4 to 3.5 for Military Tools 3.5 release

Update conda package version to 3.5

---

README.md
tools/setup.py

Merge dev to master for june release

---

tools/recipe/Important-Readme.txt

added python package readme

---

tools/setup.py

See: https://github.com/Esri/military-tools-desktop-addins/issues/120

Update Conda package version to 3.6
