.gitignore

@csmoore any interest in checking that this one works?
1) Check that there isn't a *./utils/test/log* folder in the repo
2) Run the tests:
* cd ./utils/test
* ./TestKickStart.bat
3) Afterwards, check that log folder and log files were created in *./utils/test/log*
4) Check they DON'T show up in the change list in GitHub for Windows.

updated gitignore to stop adding log files and folder to commits

---

utils/test/TestKickStart.bat
utils/test/TestRunner.py

@topowright 
Exit code from TestRunner.py is being captured in TestKickStart.bat using %ERRORLEVEL%.
This is what @ACueva will need for Jenkins to get his tests running.

Exit code from TestRunner.py captured in TestKickStart.bat

---

toolboxes/scripts/ConversionUtilities.py

Optimize polylineToPolygon by eliminating unnecessary ArcPoint unpack/copy step.
Turns out [this](https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/ec4ee02f3096ecd2ae2100a6ffa205a4a47df96d/toolboxes/scripts/ConversionUtilities.py#L130-L134) is where a majority of the slowness of this method was.

Optimize polylineToPolygon

---

toolboxes/scripts/VisibilityUtilities.py

needed to make the profile graph name match exactly what is in the key
field in the output LOS features.
simply adding the file extension to the profile graph match name seems to have worked.
Fixes issue #185 
Fixes issue #185 
Manually tested fix and verified test locally. Needs to be reviewed by @dfoll

Fix for #185

---

toolboxes/scripts/VisibilityUtilities.py

Use ExtractByMask on the elevation source with the extent of the observer buffers to reduce the amount of time the viewshed takes.
I have tested with 4 observers with a range of a 1000m in Desktop and Pro against the image service found here:
http://navigator.state.or.us/arcgis/services/Framework/Elevation_DEM_10m/ImageServer
It took about 50 secs in both applications

Address Issue #207

---

toolboxes/scripts/VisibilityUtilities.py

The observer and target location feature classes created using the AddIn both contain a field called 'offset'.
When the Linear Line of Sight tool is run it checks if the field 'OFFSET' is present, if not it adds the field to the feature class. When python checks if the field exists in the dataset it is checking for a field name called 'OFFSET' (uppercase) not 'offset' (offset lowercase), which returns false, it then tries to add the OFFSET field to the dataset which causes the error as offset exists (the database is not case sensitive, unlike python). 
Easy solution was to use the .upper() function on the field names returned from the feature class, which prevents the field from being added when it is already present

Address issue #201

---

utils/test/grg_tests/GRGCreateReferenceSystemGRGFromAreaTestCase.py

Remove: Ignore_Field_Alias option that was apparently added after 10.3 to maintain 10.3 compatibility
See:  https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/276#issuecomment-388216354 and https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/276#issuecomment-388223649

Fix broken unit test on 10.3.1

---

utils/test/grg_tests/GRGCreateGRGFromAreaTestCase.py

Added a test to check the size of each polygon based on the perimeter. Using the length and height inputs  * 2 we understand the expected perimeter. The precision of the attribute does not give us an integer and because of that it can be off by one depending on rounding. Using less than or equal to one we can confirm that each grg polygon is the size we expect it to be.
using the test that was created by @dfoll  I added a test to check the perimeter of each polygon. 
Wanted to add grg tests, but did not see the issue related to adding tests

Added GRG test for area

---

utils/test/visibility_tests/VisibilityUtilitiesTestCase.py

Adding tolerances and ommiting certain fields to allow proper comparison of raster results.
See: #275 - https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/275#issuecomment-388518803

Raster Compare test fix

---

utils/test/grg_tests/GRGCreateGRGFromPointTestCase.py

Test/tool call was locking GDB and preventing clean deletion - need to look further into cause - removing test for now while it is investigated

Removed test that is breaking harness

---

utils/test/grg_tests/GRGCreateGRGFromPointTestCase.py

Fix python 2.7.old error that popped up running test on 10.3 after merge of PR #306

Fix assertRegex for old 10.3 version python

---

toolboxes/scripts/VisibilityUtilities.py

Adding pylab.close()  to the script to prevent crashing on the closing of ArcMap and ArcScene. This has been tested both on ArcMap and ArcScene. Please do the same upon merging the pull request.
Issue addresses ArcMap and ArcScene crashing on all versions.

Adding logic to fix the issue on crash produced by LLOS

---

toolboxes/scripts/ConversionUtilities.py
utils/test/TestRunner.py

Update field type to TEXT to fix Table to Ellipse tool fail - was previously a Long.

Update field type to TEXT to fix Table to Ellipse tool fail

---

toolboxes/scripts/RangeRingUtils.py

The calculation to set the range value was being done on the temp table
that was to be joined to features to make the final output. For some
reason, it was not executing correctly. Changed it to do the calculation
on the final output feature class, and it is now working.

Calculate range distance on output after join

---

utils/test/ArcGISProTestKickStart.bat
utils/test/ArcMapTestKickStart.bat
utils/test/visibility_tests/FindLocalPeaksTestCase.py
utils/test/visibility_tests/HighestPointsTestCase.py
utils/test/visibility_tests/LinearLineOfSightTestCase.py
utils/test/visibility_tests/LowestPointsTestCase.py

Changes:
1. Add an auto/unit-test for #320
2. Add fix  failing when run standalone in Pro 2.1 (workaround for execute error if gp.checkout license called)
3. Add workaround to runner .bat for corrupted scratch gdbs

Issue #320 - add tests for no area supplied

---

toolboxes/scripts/GRGUtilities.py

This fix addresses #344.
Added logic to handle:
1. Output spatial reference of GRG
2. Removal of cell width and height from fishnet tool
Addresses #344 
GRGs were created with wrong width and height.
Tested in ArcGIS Pro 2.1 and ArcMap 10.5.1

Addresses #344

---

toolboxes/scripts/VisibilityUtilities.py

See: #345 
On recent versions of ArcGIS (Pro 2.1, ArcMap 10.6) calling GetCount_management on the raster surface produced by Find Local Peaks tool was failing and causing tool to fail.
Added workaround recommended in #345 [workaround](https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/345#issuecomment-399604207)  
See: #345 
See: #345 
Manual

Implement workaround(s) for GetCount failure in Find Local Peaks

---

tools/militarytools/esri/toolboxes/scripts/ConversionUtilities.py

This fix addresses #388. `originTableFieldNames` in [line 578](https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/tools/militarytools/esri/toolboxes/scripts/ConversionUtilities.py#L578) was the issue.

Addresses #388

---

tools/militarytools/esri/toolboxes/scripts/RangeRingUtils.py
tools/militarytools/esri/toolboxes/scripts/RangeRingsFromInterval.py
utils/test/distance_tests/RangeRingUtilsTestCase.py

See Issue #384 
Changes:
1. #384 - allow radials = 0
2. Add better error checking for values
3. Add test cases for error checking
Show behave like this now:

Allow radials to be set to zero from RangeRing tools

---

tools/militarytools/esri/toolboxes/scripts/ConversionUtilities.py

#418 - fix crash in TableToPolygon tool if geometry is empty. See comment: https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/418#issuecomment-504097829

Add check for empty geom/shape to TableToPolygon
